// apps/web/src/components/ChangePasswordForm.vue
<script setup>
import { ref } from 'vue'
import { KeyRound, LoaderCircle } from 'lucide-vue-next'
import { authService } from '../services/authService'
import { extractErrorMessage } from '../helpers/errorHandler'

const password = ref('')
const confirmPassword = ref('')
const submitting = ref(false)
const errorMessage = ref('')
const successMessage = ref('')

async function handleSubmit() {
  errorMessage.value = ''
  successMessage.value = ''

  if (password.value.length < 6) {
    errorMessage.value = 'Mật khẩu tối thiểu 6 ký tự'
    return
  }

  if (password.value !== confirmPassword.value) {
    errorMessage.value = 'Mật khẩu xác nhận không khớp'
    return
  }

  submitting.value = true
  try {
    await authService.updateMyPassword(password.value)
    successMessage.value = 'Đổi mật khẩu thành công!'
    password.value = ''
    confirmPassword.value = ''
  } catch (error) {
    errorMessage.value = extractErrorMessage(error)
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <div class="card profile-card">
    <div class="card__header">
      <h2 class="card-title">
        <KeyRound :size="20" />
        Đổi mật khẩu
      </h2>
    </div>
    <div class="card__body">
      <form class="flex-col gap-4" @submit.prevent="handleSubmit">
        <div v-if="errorMessage" class="alert alert--error">{{ errorMessage }}</div>
        <div v-if="successMessage" class="alert alert--success">{{ successMessage }}</div>

        <div class="form-group mb-0">
          <label class="form-label" for="newPassword">Mật khẩu mới</label>
          <input
            id="newPassword"
            v-model="password"
            class="form-input"
            type="password"
            placeholder="Tối thiểu 6 ký tự"
            required
          />
        </div>

        <div class="form-group mb-0">
          <label class="form-label" for="confirmNewPassword">Xác nhận mật khẩu</label>
          <input
            id="confirmNewPassword"
            v-model="confirmPassword"
            class="form-input"
            type="password"
            placeholder="Nhập lại mật khẩu mới"
            required
          />
        </div>

        <button type="submit" class="btn btn--primary fit-content" :disabled="submitting">
          <LoaderCircle v-if="submitting" class="spin mr-2" :size="16" />
          Cập nhật mật khẩu
        </button>
      </form>
    </div>
  </div>
</template>

<style scoped>
.profile-card {
  max-width: 32rem;
}

.card-title {
  display: flex;
  align-items: center;
  gap: var(--spacing-2);
  font-size: var(--font-size-lg);
  margin: 0;
}
</style>

// apps/web/src/components/shared/ChangePasswordForm.tsx
/**
 * ChangePasswordForm
 * Component dùng chung cho tất cả role để đổi mật khẩu.
 * API: PUT /api/v1/me/password
 */
"use client";

import React, { useState } from "react";
import { authApi } from "@/lib/api/auth.api";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { KeyRound, Loader2 } from "lucide-react";
import { extractApiErrorMessage } from "@/lib/api-error";

export function ChangePasswordForm() {
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (password.length < 6) { setError("Mật khẩu tối thiểu 6 ký tự"); return; }
    if (password !== confirmPassword) { setError("Mật khẩu xác nhận không khớp"); return; }

    try {
      setSubmitting(true); setError(""); setSuccess("");
      await authApi.updateMyPassword(password);
      setSuccess("Đổi mật khẩu thành công!");
      setPassword(""); setConfirmPassword("");
    } catch (error: unknown) {
      setError(extractApiErrorMessage(error, "Không thể đổi mật khẩu"));
    } finally { setSubmitting(false); }
  };

  return (
    <Card className="max-w-lg">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <KeyRound className="h-5 w-5" /> Đổi mật khẩu
        </CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          {error && <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
          {success && <div className="rounded-md bg-success/10 p-3 text-sm text-success">{success}</div>}
          <div className="space-y-2">
            <label htmlFor="newPassword" className="text-sm font-medium">Mật khẩu mới</label>
            <Input id="newPassword" type="password" placeholder="Tối thiểu 6 ký tự" value={password} onChange={(e) => setPassword(e.target.value)} required />
          </div>
          <div className="space-y-2">
            <label htmlFor="confirmNewPassword" className="text-sm font-medium">Xác nhận mật khẩu</label>
            <Input id="confirmNewPassword" type="password" placeholder="Nhập lại mật khẩu mới" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} required />
          </div>
          <Button type="submit" disabled={submitting}>
            {submitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Cập nhật mật khẩu
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
