// apps/web/src/views/ChatPage.vue
<script setup>
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { ArrowLeft, LoaderCircle, MessageSquare, Plus, Search, Send, X } from 'lucide-vue-next'
import {
  useChatWebSocket,
  useChatConversations,
  useChatMessages,
  useChatSearch,
} from '../composables/chat'
import {
  getConversationId,
  getInitials,
  getConversationName,
  isFirstInGroup,
  isLastInGroup,
  shouldShowSenderName,
  getSenderName,
  parseJwtPayload,
  getAuthToken,
} from '../helpers/chatHelpers'
import { extractErrorMessage } from '../helpers/errorHandler'

const { isConnected, connect, sendMessage: wsSendMessage, onMessage } = useChatWebSocket()
const {
  conversations,
  selectedConversation,
  loading,
  fetchConversations,
  selectConversation,
  createDirectConversation,
  createGroupConversation,
  getSelectedConversationId,
} = useChatConversations()
const {
  messages,
  loadingMessages,
  loadingMore,
  hasMore,
  loadMessages,
  loadOlderMessages,
  addMessage,
} = useChatMessages()
const { searchQuery, searchResults, showNewConversation, toggleNewConversation, clearSearch } =
  useChatSearch()

const newChatMode = ref('direct')
const groupName = ref('')
const groupMembers = ref([])
const groupSubmitting = ref(false)
const groupError = ref('')
const directError = ref('')

const input = ref('')
const currentUserId = ref('')
const messagesContainer = ref(null)
const messagesEnd = ref(null)

const selectedConversationId = computed(() => getSelectedConversationId())
const visibleConversations = computed(() => conversations.value.filter(Boolean))
const visibleSearchResults = computed(() => searchResults.value.filter(Boolean))
const composerDisabled = computed(() => !selectedConversationId.value || !isConnected.value)
const composerHint = computed(() => {
  if (!selectedConversationId.value) return 'Chọn một cuộc trò chuyện để bắt đầu nhắn tin.'
  if (!isConnected.value) return 'Mất kết nối. Vui lòng chờ hệ thống tự kết nối lại.'
  return ''
})

function scrollToBottom(behavior = 'smooth') {
  messagesEnd.value?.scrollIntoView({ behavior })
}

function handleSendMessage() {
  const content = input.value.trim()
  if (!content || composerDisabled.value) return

  const sent = wsSendMessage(selectedConversationId.value, content)
  if (sent) {
    input.value = ''
  }
}

function handleKeydown(event) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    handleSendMessage()
  }
}

async function handleLoadMessages(conversation) {
  selectConversation(conversation)
  await loadMessages(getConversationId(conversation))
  await nextTick()
  scrollToBottom('auto')
}

async function handleStartConversation(userId) {
  directError.value = ''
  try {
    const conversation = await createDirectConversation(userId)
    if (conversation) {
      clearSearch()
      if (showNewConversation.value) toggleNewConversation()
      await handleLoadMessages(conversation)
    }
  } catch (err) {
    directError.value = extractErrorMessage(err)
  }
}

function addGroupMember(user) {
  if (!user?.user_id || user.user_id === currentUserId.value) return
  if (groupMembers.value.some((m) => m.user_id === user.user_id)) return
  groupMembers.value = [...groupMembers.value, user]
}

function removeGroupMember(userId) {
  groupMembers.value = groupMembers.value.filter((m) => m.user_id !== userId)
}

async function handleCreateGroup() {
  groupError.value = ''
  if (groupMembers.value.length < 1) {
    groupError.value = 'Thêm ít nhất một thành viên để tạo nhóm.'
    return
  }
  groupSubmitting.value = true
  try {
    const conv = await createGroupConversation(
      groupName.value,
      groupMembers.value.map((m) => m.user_id),
    )
    if (conv) {
      clearSearch()
      if (showNewConversation.value) toggleNewConversation()
      await handleLoadMessages(conv)
    }
  } catch (err) {
    groupError.value = extractErrorMessage(err)
  } finally {
    groupSubmitting.value = false
  }
}

function handleScroll() {
  loadOlderMessages(selectedConversationId.value, messagesContainer.value)
}

watch(messages, async () => {
  await nextTick()
  const container = messagesContainer.value
  if (!container) return
  const isNearBottom = container.scrollHeight - container.scrollTop - container.clientHeight < 120
  if (isNearBottom) scrollToBottom()
})

watch(showNewConversation, (open) => {
  if (!open) {
    newChatMode.value = 'direct'
    groupName.value = ''
    groupMembers.value = []
    groupError.value = ''
    directError.value = ''
    groupSubmitting.value = false
  }
})

watch(newChatMode, () => {
  groupError.value = ''
  directError.value = ''
})

onMounted(async () => {
  const token = getAuthToken()
  const payload = token ? parseJwtPayload(token) : null
  currentUserId.value = payload?.user_id || ''

  connect()
  onMessage((message) => {
    if (message.conversation_id === selectedConversationId.value) {
      addMessage(message)
    }
  })

  await fetchConversations()
})
</script>

<template>
  <div class="chat-page">
    <aside class="chat-sidebar" :class="{ 'chat-sidebar--hidden': selectedConversation }">
      <div class="chat-sidebar__header">
        <h1>Tin nhắn</h1>
        <div class="chat-header-actions">
          <div
            class="connection-pill"
            :class="isConnected ? 'connection-pill--online' : 'connection-pill--offline'"
          >
            <span class="connection-dot"></span>
            <span>{{ isConnected ? 'Online' : 'Offline' }}</span>
          </div>
          <button
            class="new-chat-button"
            type="button"
            :title="showNewConversation ? 'Đóng' : 'Tạo mới'"
            @click="toggleNewConversation"
          >
            <X v-if="showNewConversation" :size="20" />
            <Plus v-else :size="20" />
          </button>
        </div>
      </div>

      <div v-if="showNewConversation" class="new-conversation-panel">
        <div class="new-chat-tabs" role="tablist">
          <button
            type="button"
            class="new-chat-tab"
            role="tab"
            :aria-selected="newChatMode === 'direct'"
            @click="newChatMode = 'direct'"
          >
            Trực tiếp
          </button>
          <button
            type="button"
            class="new-chat-tab"
            role="tab"
            :aria-selected="newChatMode === 'group'"
            @click="newChatMode = 'group'"
          >
            Nhóm
          </button>
        </div>

        <div class="search-box">
          <Search :size="16" />
          <input v-model="searchQuery" placeholder="Tìm kiếm email hoặc tên..." />
        </div>

        <template v-if="newChatMode === 'direct'">
          <p v-if="directError" class="group-inline-error">{{ directError }}</p>
          <div v-if="visibleSearchResults.length > 0" class="search-results">
            <button
              v-for="user in visibleSearchResults"
              :key="user.user_id"
              type="button"
              class="conversation-item"
              @click="handleStartConversation(user.user_id)"
            >
              <div class="avatar">{{ getInitials(user.full_name || user.email) }}</div>
              <div class="conversation-copy">
                <p>{{ user.full_name || user.email }}</p>
                <span>{{ user.email }}</span>
              </div>
            </button>
          </div>
        </template>

        <template v-else>
          <input
            v-model="groupName"
            type="text"
            class="group-name-input"
            maxlength="255"
            placeholder="Tên nhóm (tuỳ chọn)"
            aria-label="Tên nhóm"
          />
          <div v-if="groupMembers.length > 0" class="member-chips">
            <span v-for="m in groupMembers" :key="m.user_id" class="member-chip">
              {{ m.full_name || m.email }}
              <button type="button" class="chip-remove" @click="removeGroupMember(m.user_id)">
                <X :size="14" />
              </button>
            </span>
          </div>
          <p v-if="groupError" class="group-inline-error">{{ groupError }}</p>
          <button
            type="button"
            class="create-group-submit"
            :disabled="groupSubmitting || groupMembers.length < 1"
            @click="handleCreateGroup"
          >
            <LoaderCircle v-if="groupSubmitting" class="spin" :size="18" />
            <span>{{ groupSubmitting ? 'Đang tạo...' : 'Tạo nhóm' }}</span>
          </button>
          <div v-if="visibleSearchResults.length > 0" class="search-results">
            <button
              v-for="user in visibleSearchResults"
              :key="user.user_id"
              type="button"
              class="conversation-item"
              :disabled="
                groupMembers.some((m) => m.user_id === user.user_id) || user.user_id === currentUserId
              "
              @click="addGroupMember(user)"
            >
              <div class="avatar">{{ getInitials(user.full_name || user.email) }}</div>
              <div class="conversation-copy">
                <p>{{ user.full_name || user.email }}</p>
                <span>{{
                  groupMembers.some((m) => m.user_id === user.user_id)
                    ? 'Đã thêm'
                    : 'Chạm để thêm vào nhóm'
                }}</span>
              </div>
            </button>
          </div>
        </template>
      </div>

      <div v-if="loading" class="chat-loading">
        <LoaderCircle class="spin" :size="24" />
      </div>

      <div v-else-if="visibleConversations.length === 0" class="chat-empty">
        <MessageSquare :size="32" />
        <p>Chưa có tin nhắn nào</p>
      </div>

      <div v-else class="conversation-list">
        <button
          v-for="conversation in visibleConversations"
          :key="getConversationId(conversation)"
          type="button"
          class="conversation-item"
          :class="{
            'conversation-item--active': selectedConversationId === getConversationId(conversation),
          }"
          @click="handleLoadMessages(conversation)"
        >
          <div class="avatar">
            {{ getInitials(getConversationName(conversation, currentUserId)) }}
          </div>
          <div class="conversation-copy">
            <p>{{ getConversationName(conversation, currentUserId) }}</p>
            <span>{{
              conversation.type === 'direct'
                ? 'Trò chuyện trực tiếp'
                : `Nhóm ${conversation.participants?.length || 0} thành viên`
            }}</span>
          </div>
        </button>
      </div>
    </aside>

    <section class="chat-area" :class="{ 'chat-area--active': selectedConversation }">
      <template v-if="selectedConversation">
        <header class="chat-area__header">
          <button type="button" class="back-button" @click="selectConversation(null)">
            <ArrowLeft :size="24" />
          </button>
          <div class="avatar avatar--primary">
            {{ getInitials(getConversationName(selectedConversation, currentUserId)) }}
          </div>
          <div class="conversation-copy">
            <p>{{ getConversationName(selectedConversation, currentUserId) }}</p>
            <span>{{
              selectedConversation.type === 'direct'
                ? 'Đang trực tuyến'
                : `${selectedConversation.participants?.length || 0} thành viên`
            }}</span>
          </div>
        </header>

        <div ref="messagesContainer" class="message-list" @scroll="handleScroll">
          <div v-if="loadingMore" class="history-loading">
            <LoaderCircle class="spin" :size="16" />
            Đang tải lịch sử...
          </div>

          <div v-if="!hasMore && messages.length > 0" class="conversation-start">
            Khởi đầu cuộc trò chuyện
          </div>

          <div v-if="loadingMessages" class="chat-loading">
            <LoaderCircle class="spin" :size="24" />
          </div>

          <div v-else-if="messages.length === 0" class="message-empty">
            <MessageSquare :size="40" />
            <p>Gửi lời chào đầu tiên!</p>
          </div>

          <div v-else class="messages">
            <div
              v-for="(message, index) in messages"
              :key="message.message_id"
              class="message-bubble"
              :class="{
                'message-bubble--mine': message.sender_id === currentUserId,
                'message-bubble--first': isFirstInGroup(messages, index),
                'message-bubble--last': isLastInGroup(messages, index),
              }"
            >
              <span
                v-if="
                  shouldShowSenderName(
                    message,
                    index,
                    messages,
                    selectedConversation?.type,
                    currentUserId,
                  )
                "
                class="message-sender"
              >
                {{ getSenderName(message) }}
              </span>
              <p>{{ message.content }}</p>
              <span>{{
                new Date(message.created_at).toLocaleTimeString('vi-VN', {
                  hour: '2-digit',
                  minute: '2-digit',
                })
              }}</span>
            </div>
          </div>
          <div ref="messagesEnd"></div>
        </div>

        <footer class="composer">
          <button type="button" class="attach-button" disabled title="Sắp hỗ trợ gửi tệp">
            <Plus :size="24" />
          </button>
          <textarea
            v-model="input"
            rows="1"
            placeholder="Nhắn tin..."
            :disabled="composerDisabled"
            @keydown="handleKeydown"
          ></textarea>
          <button
            type="button"
            class="send-button"
            :disabled="!input.trim() || composerDisabled"
            @click="handleSendMessage"
          >
            <Send :size="20" />
          </button>
        </footer>
        <p v-if="composerHint" class="composer-hint">{{ composerHint }}</p>
      </template>

      <div v-else class="chat-placeholder">
        <div class="placeholder-icon">
          <MessageSquare :size="40" />
        </div>
        <h2>Ứng dụng Nhắn tin IRIS</h2>
        <p>Chọn một cuộc trò chuyện để bắt đầu</p>
      </div>
    </section>
  </div>
</template>

<style scoped>
.chat-page {
  position: relative;
  display: flex;
  height: calc(100dvh - var(--header-height) - 2rem);
  min-height: 520px;
  width: 100%;
  overflow: hidden;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: var(--color-background);
}

.chat-sidebar {
  width: 100%;
  max-width: 380px;
  border-right: 1px solid var(--color-border);
  background: var(--color-surface);
  display: flex;
  flex-direction: column;
}

.chat-sidebar__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--spacing-3);
  padding: var(--spacing-4);
  border-bottom: 1px solid var(--color-border);
}

.chat-sidebar__header h1,
.conversation-copy p,
.conversation-copy span,
.message-bubble p,
.message-bubble span,
.chat-placeholder h2,
.chat-placeholder p {
  margin: 0;
}

.chat-sidebar__header h1 {
  font-size: var(--font-size-2xl);
}

.chat-header-actions {
  display: flex;
  align-items: center;
  gap: var(--spacing-3);
}

.connection-pill {
  display: flex;
  align-items: center;
  gap: var(--spacing-1);
  border-radius: var(--radius-full);
  padding: var(--spacing-1) var(--spacing-2);
  background: var(--color-background);
  color: var(--color-text-muted);
  font-size: 0.65rem;
  font-weight: 800;
  letter-spacing: 0;
  text-transform: uppercase;
}

.connection-pill--online {
  color: var(--color-success);
  background: color-mix(in srgb, var(--color-success) 12%, transparent);
}

.connection-dot {
  width: 0.5rem;
  height: 0.5rem;
  border-radius: var(--radius-full);
  background: currentColor;
}

.new-chat-button {
  width: 2.25rem;
  height: 2.25rem;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 0;
  border-radius: var(--radius-full);
  background: color-mix(in srgb, var(--color-primary) 12%, transparent);
  color: var(--color-primary);
}

.new-chat-button:hover {
  background: color-mix(in srgb, var(--color-primary) 20%, transparent);
}

.new-conversation-panel {
  padding: var(--spacing-3);
  border-bottom: 1px solid var(--color-border);
}

.new-chat-tabs {
  display: flex;
  gap: var(--spacing-2);
  margin-bottom: var(--spacing-3);
}

.new-chat-tab {
  flex: 1;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-full);
  padding: var(--spacing-2) var(--spacing-3);
  background: transparent;
  color: var(--color-text-muted);
  font-size: var(--font-size-xs);
  font-weight: 700;
  cursor: pointer;
}

.new-chat-tab[aria-selected='true'] {
  background: color-mix(in srgb, var(--color-primary) 14%, transparent);
  color: var(--color-primary);
  border-color: transparent;
}

.group-name-input {
  width: 100%;
  box-sizing: border-box;
  margin-bottom: var(--spacing-2);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-full);
  padding: var(--spacing-2) var(--spacing-3);
  font-size: var(--font-size-sm);
  background: var(--color-background);
  color: var(--color-text);
}

.member-chips {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-2);
  margin-bottom: var(--spacing-2);
}

.member-chip {
  display: inline-flex;
  align-items: center;
  gap: var(--spacing-1);
  padding: var(--spacing-1) var(--spacing-2);
  border-radius: var(--radius-full);
  background: var(--color-background);
  font-size: var(--font-size-xs);
  font-weight: 600;
}

.chip-remove {
  display: flex;
  align-items: center;
  justify-content: center;
  border: 0;
  background: transparent;
  color: var(--color-text-muted);
  padding: 0;
  cursor: pointer;
  border-radius: var(--radius-full);
}

.chip-remove:hover {
  color: var(--color-text);
}

.group-inline-error {
  margin: 0 0 var(--spacing-2);
  font-size: var(--font-size-xs);
  color: var(--color-danger);
}

.create-group-submit {
  width: 100%;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--spacing-2);
  margin-bottom: var(--spacing-2);
  border: 0;
  border-radius: var(--radius-full);
  padding: var(--spacing-3);
  background: var(--color-primary);
  color: var(--color-on-primary);
  font-weight: 700;
  font-size: var(--font-size-sm);
  cursor: pointer;
}

.create-group-submit:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

.conversation-item:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.search-box {
  display: flex;
  align-items: center;
  gap: var(--spacing-2);
  padding: var(--spacing-2) var(--spacing-3);
  border-radius: var(--radius-full);
  border: 1px solid var(--color-border);
  color: var(--color-text-muted);
}

.search-box input {
  min-width: 0;
  flex: 1;
  border: 0;
  background: transparent;
  color: var(--color-text);
  outline: none;
}

.search-results {
  overflow: hidden;
  margin-top: var(--spacing-2);
  border: 1px solid var(--color-border);
  border-radius: 1rem;
  background: var(--color-surface);
}

.conversation-list {
  overflow-y: auto;
  padding: var(--spacing-2);
}

.conversation-item {
  width: 100%;
  display: flex;
  align-items: center;
  gap: var(--spacing-3);
  border: 0;
  border-radius: 1rem;
  background: transparent;
  color: var(--color-text);
  padding: var(--spacing-3);
  text-align: left;
  transition: background-color 0.2s;
}

.conversation-item:hover {
  background: var(--color-background);
}

.conversation-item--active {
  background: var(--color-primary);
  color: var(--color-on-primary);
}

.conversation-copy {
  min-width: 0;
  flex: 1;
}

.conversation-copy p {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-weight: 700;
  font-size: var(--font-size-sm);
}

.conversation-copy span {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: var(--color-text-muted);
  font-size: var(--font-size-xs);
}

.conversation-item--active .conversation-copy span {
  color: var(--color-on-primary-muted);
}

.avatar {
  width: 3rem;
  height: 3rem;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-full);
  background: var(--color-background);
  color: var(--color-text-muted);
  font-weight: 800;
}

.avatar--primary {
  width: 2.5rem;
  height: 2.5rem;
  background: var(--color-primary);
  color: var(--color-on-primary);
}

.chat-area {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  background: var(--color-background);
}

.chat-area__header {
  display: flex;
  align-items: center;
  gap: var(--spacing-3);
  padding: var(--spacing-3);
  border-bottom: 1px solid var(--color-border);
  background: color-mix(in srgb, var(--color-background) 82%, transparent);
  backdrop-filter: blur(12px);
}

.back-button {
  display: none;
  border: 0;
  background: transparent;
  color: var(--color-primary);
  border-radius: var(--radius-full);
  padding: var(--spacing-2);
}

.message-list {
  flex: 1;
  overflow-y: auto;
  padding: var(--spacing-4);
}

.messages {
  display: flex;
  flex-direction: column;
  gap: 0.125rem;
}

.message-bubble {
  max-width: min(78%, 36rem);
  align-self: flex-start;
  border-radius: 1.25rem;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  padding: var(--spacing-2) var(--spacing-3);
}

.message-bubble--first {
  margin-top: var(--spacing-3);
}

.message-bubble--mine {
  align-self: flex-end;
  background: var(--color-primary);
  color: var(--color-on-primary);
  border-color: var(--color-primary);
}

.message-sender {
  display: block;
  margin-bottom: var(--spacing-1);
  color: var(--color-primary);
  font-size: 0.68rem;
  font-weight: 800;
}

.message-bubble p {
  white-space: pre-line;
  font-size: var(--font-size-sm);
}

.message-bubble span {
  display: block;
  margin-top: var(--spacing-1);
  font-size: 0.68rem;
  opacity: 0.72;
}

.composer {
  display: flex;
  align-items: flex-end;
  gap: var(--spacing-2);
  padding: var(--spacing-3);
  border-top: 1px solid var(--color-border);
  background: var(--color-surface);
}

.composer-hint {
  margin: 0;
  padding: 0 var(--spacing-3) var(--spacing-3);
  color: var(--color-text-muted);
  font-size: var(--font-size-xs);
}

.composer textarea {
  min-height: 2.75rem;
  max-height: 7.5rem;
  flex: 1;
  resize: none;
  border: 1px solid transparent;
  border-radius: 1.4rem;
  background: var(--color-background);
  color: var(--color-text);
  padding: var(--spacing-3) var(--spacing-4);
  outline: none;
}

.composer textarea:focus {
  border-color: var(--color-primary);
  background: var(--color-surface);
}

.attach-button,
.send-button {
  width: 2.75rem;
  height: 2.75rem;
  border: 0;
  border-radius: var(--radius-full);
  display: flex;
  align-items: center;
  justify-content: center;
}

.attach-button {
  background: transparent;
  color: var(--color-text-muted);
}

.attach-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.send-button {
  background: var(--color-primary);
  color: var(--color-on-primary);
}

.send-button:disabled {
  background: var(--color-background);
  color: var(--color-text-muted);
}

.chat-loading,
.chat-empty,
.message-empty,
.chat-placeholder,
.history-loading {
  display: flex;
  align-items: center;
  justify-content: center;
}

.chat-loading,
.chat-empty,
.message-empty,
.chat-placeholder {
  flex-direction: column;
  gap: var(--spacing-3);
  color: var(--color-text-muted);
  padding: 2rem;
  text-align: center;
}

.chat-placeholder {
  height: 100%;
}

.placeholder-icon {
  width: 6rem;
  height: 6rem;
  border-radius: var(--radius-full);
  background: var(--color-surface);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--color-primary);
}

.history-loading {
  gap: var(--spacing-2);
  margin: 0 auto var(--spacing-3);
  width: fit-content;
  border-radius: var(--radius-full);
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  padding: var(--spacing-1) var(--spacing-3);
  color: var(--color-text-muted);
  font-size: var(--font-size-xs);
}

.conversation-start {
  width: fit-content;
  margin: 0 auto var(--spacing-4);
  border-radius: var(--radius-lg);
  background: var(--color-surface);
  color: var(--color-text-muted);
  padding: var(--spacing-1) var(--spacing-3);
  font-size: 0.68rem;
  font-weight: 700;
  text-transform: uppercase;
}

.spin {
  animation: spin 1s linear infinite;
}

@media (max-width: 767px) {
  .chat-page {
    height: calc(100dvh - var(--header-height) - 1rem);
    border-radius: 0;
    border-left: 0;
    border-right: 0;
  }

  .chat-sidebar {
    max-width: none;
    transition: transform 0.25s ease;
  }

  .chat-sidebar--hidden {
    transform: translateX(-100%);
  }

  .chat-area {
    position: absolute;
    inset: 0;
    transform: translateX(100%);
    transition: transform 0.25s ease;
  }

  .chat-area--active {
    transform: translateX(0);
  }

  .back-button {
    display: flex;
  }
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>

// apps/web/src/components/shared/ChatPage.tsx
/**
 * ChatPage Component
 * Trang chat realtime dùng chung cho tất cả roles (Admin, Teacher, Parent).
 * Giao diện split-pane: danh sách hội thoại bên trái, khung chat bên phải.
 *
 * Sử dụng cursor-based pagination: load 50 tin nhắn mới nhất ban đầu,
 * sau đó tải thêm khi user cuộn lên đầu (infinite scroll ngược chiều).
 */
"use client";

import React, { useState, useEffect, useRef, useCallback } from "react";
import { chatApi } from "@/lib/api/chat.api";
import { authHelpers } from "@/lib/api/client";
import { useChatWebSocket } from "@/hooks/useChatWebSocket";
import { Conversation, Message } from "@/types";
import { MessageSquare, Send, ArrowLeft, Wifi, WifiOff, Plus, X, Loader2 } from "lucide-react";

/* ────────────────────────────── helpers ────────────────────────────── */

/** parseJwtPayload giải mã phần payload của JWT token (không xác thực chữ ký) */
function parseJwtPayload(token: string): { user_id: string; email: string } | null {
  try {
    const base64 = token.split(".")[1];
    const json = atob(base64.replace(/-/g, "+").replace(/_/g, "/"));
    return JSON.parse(json);
  } catch {
    return null;
  }
}

/** formatTime hiển thị thời gian ngắn gọn (HH:mm) */
function formatTime(iso: string) {
  return new Date(iso).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" });
}

/* ────────────────────────────── component ────────────────────────────── */

export default function ChatPage() {
  /* ── state ── */
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [selectedConv, setSelectedConv] = useState<Conversation | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(true);
  const [currentUserId, setCurrentUserId] = useState<string>("");
  const [showNewConv, setShowNewConv] = useState(false);
  const [newConvTarget, setNewConvTarget] = useState("");
  const [searchResults, setSearchResults] = useState<{ user_id: string; email: string; full_name: string }[]>([]);

  // Cursor-based pagination state
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const messagesContainerRef = useRef<HTMLDivElement>(null);

  /* ── lấy user id từ JWT ── */
  useEffect(() => {
    const token = authHelpers.getToken();
    if (token) {
      const payload = parseJwtPayload(token);
      if (payload) setCurrentUserId(payload.user_id);
    }
  }, []);

  /* ── WebSocket ── */
  const handleNewMessage = useCallback((msg: Message) => {
    setMessages((prev) => {
      // Chỉ thêm nếu tin nhắn thuộc cuộc hội thoại đang xem
      if (prev.length > 0 && prev[0]?.conversation_id === msg.conversation_id) {
        // Tránh duplicate
        if (prev.some((m) => m.message_id === msg.message_id)) return prev;
        return [...prev, msg];
      }
      return prev;
    });
  }, []);

  const { isConnected, sendMessage } = useChatWebSocket(handleNewMessage);

  /* ── fetch conversations ── */
  const fetchConversations = useCallback(async () => {
    try {
      setLoading(true);
      const data = await chatApi.listConversations();
      setConversations(data || []);
    } catch (err) {
      console.error("Failed to load conversations:", err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchConversations();
  }, [fetchConversations]);

  /* ── fetch messages khi chọn conversation (lần đầu) ── */
  useEffect(() => {
    if (!selectedConv) return;
    setMessages([]);
    setNextCursor(null);
    setHasMore(false);

    (async () => {
      try {
        const res = await chatApi.listMessages(selectedConv.conversation_id);
        // API trả về DESC (mới nhất trước) → reverse để hiển thị đúng thứ tự
        setMessages([...(res.data || [])].reverse());
        setNextCursor(res.next_cursor);
        setHasMore(res.has_more);
      } catch (err) {
        console.error("Failed to load messages:", err);
      }
    })();
  }, [selectedConv]);

  /* ── auto scroll xuống cuối khi có tin nhắn mới ── */
  const prevMessageCountRef = useRef(0);
  useEffect(() => {
    const container = messagesContainerRef.current;
    if (!container) return;

    const newCount = messages.length;
    const wasAtBottom =
      container.scrollHeight - container.scrollTop - container.clientHeight < 100;

    // Chỉ scroll xuống nếu user đang ở gần cuối (tin nhắn mới đến)
    // hoặc đây là lần đầu load (prevCount = 0)
    if (wasAtBottom || prevMessageCountRef.current === 0) {
      messagesEndRef.current?.scrollIntoView({ behavior: prevMessageCountRef.current === 0 ? "auto" : "smooth" });
    }
    prevMessageCountRef.current = newCount;
  }, [messages]);

  /* ── load more khi user cuộn lên đầu ── */
  const handleScroll = useCallback(async () => {
    const container = messagesContainerRef.current;
    if (!container || !hasMore || loadingMore || !selectedConv || !nextCursor) return;

    // Khi scroll gần đầu (< 80px)
    if (container.scrollTop < 80) {
      setLoadingMore(true);
      const prevScrollHeight = container.scrollHeight;
      try {
        const res = await chatApi.listMessages(selectedConv.conversation_id, 50, nextCursor);
        const older = [...(res.data || [])].reverse(); // reverse về ASC
        setMessages((prev) => [...older, ...prev]);
        setNextCursor(res.next_cursor);
        setHasMore(res.has_more);

        // Giữ nguyên vị trí scroll sau khi prepend tin nhắn cũ
        requestAnimationFrame(() => {
          if (container) {
            container.scrollTop = container.scrollHeight - prevScrollHeight;
          }
        });
      } catch (err) {
        console.error("Failed to load more messages:", err);
      } finally {
        setLoadingMore(false);
      }
    }
  }, [hasMore, loadingMore, selectedConv, nextCursor]);

  /* ── gửi tin nhắn ── */
  const handleSend = () => {
    if (!input.trim() || !selectedConv) return;
    sendMessage(selectedConv.conversation_id, input.trim());
    setInput("");
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  /* ── tên hiển thị của conversation ── */
  const getConvDisplayName = (conv: Conversation) => {
    if (conv.name) return conv.name;
    if (conv.participants) {
      const other = conv.participants.find((p) => p.user_id !== currentUserId);
      return other?.full_name || other?.email || "Cuộc hội thoại";
    }
    return "Cuộc hội thoại";
  };

  /* ── tìm kiếm user debounce ── */
  useEffect(() => {
    if (!newConvTarget.trim()) {
      setSearchResults([]);
      return;
    }
    const timer = setTimeout(async () => {
      try {
        const results = await chatApi.searchUsers(newConvTarget.trim());
        setSearchResults(results || []);
      } catch (err) {
        console.error("Failed to search users:", err);
      }
    }, 500);
    return () => clearTimeout(timer);
  }, [newConvTarget]);

  /* ── tạo cuộc hội thoại mới bằng user_id cụ thể ── */
  const startConversation = async (targetUserId: string) => {
    if (!targetUserId) return;
    try {
      const newConv = await chatApi.createDirectConversation(targetUserId);
      await fetchConversations();
      setSelectedConv(newConv);
      setShowNewConv(false);
      setNewConvTarget("");
      setSearchResults([]);
    } catch (err) {
      console.error(err);
      alert("Không thể tạo cuộc trò chuyện: " + (err as Error).message);
    }
  };

  /* ── Ảo hóa Avatar từ tên ── */
  const getInitials = (name: string) => {
    return name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .substring(0, 2)
      .toUpperCase();
  };

  /* ────────────────────────────── render ────────────────────────────── */

  return (
    <div className="relative flex h-[100dvh] md:h-[calc(100vh-3.5rem)] bg-white dark:bg-zinc-950 overflow-hidden">
      {/* ── Sidebar: Danh sách cuộc hội thoại ── */}
      <div className="flex w-full md:w-80 flex-col border-r border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 z-0 h-full">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-4 md:py-5 border-b border-transparent">
          <h2 className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
            Tin nhắn
          </h2>
          <div className="flex items-center gap-3">
            {isConnected ? (
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-950/30">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                </span>
                <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-500 uppercase tracking-widest hidden md:inline-block">Online</span>
              </div>
            ) : (
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-zinc-100 dark:bg-zinc-900">
                <WifiOff className="h-3 w-3 text-zinc-500" />
                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest hidden md:inline-block">Offline</span>
              </div>
            )}
            <button
              onClick={() => setShowNewConv(!showNewConv)}
              className="rounded-full bg-blue-50 dark:bg-blue-900/30 p-2 text-blue-600 dark:text-blue-400 hover:bg-blue-100 dark:hover:bg-blue-900/50 transition-colors"
              title="Tạo mới"
            >
              {showNewConv ? <X className="h-5 w-5" /> : <Plus className="h-5 w-5" />}
            </button>
          </div>
        </div>

        {/* Form tạo mới */}
        {showNewConv && (
          <div className="px-4 pb-4 animate-in fade-in slide-in-from-top-2 duration-200">
            <div className="relative">
              <input
                type="text"
                placeholder="Tìm kiếm email hoặc tên..."
                value={newConvTarget}
                onChange={(e) => setNewConvTarget(e.target.value)}
                className="w-full rounded-2xl border-none bg-zinc-100 dark:bg-zinc-900 px-4 py-2.5 pl-10 text-sm text-zinc-900 dark:text-zinc-100 placeholder-zinc-500 focus:ring-2 focus:ring-blue-500 focus:bg-white dark:focus:bg-zinc-950 transition-all outline-none"
              />
              <MessageSquare className="absolute left-4 top-2.5 h-4 w-4 text-zinc-400" />
            </div>
            {/* Dropdown tìm kiếm */}
            {searchResults.length > 0 && (
              <div className="mt-2 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl shadow-xl overflow-hidden animate-in fade-in duration-200">
                {searchResults.map((user) => (
                  <button
                    key={user.user_id}
                    onClick={() => startConversation(user.user_id)}
                    className="w-full text-left px-4 py-3 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors flex items-center gap-3 border-b border-zinc-100 dark:border-zinc-800 last:border-0"
                  >
                    <div className="h-10 w-10 flex-shrink-0 rounded-full bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center text-white font-bold shadow-sm">
                      {getInitials(user.full_name || user.email)}
                    </div>
                    <div className="flex flex-col overflow-hidden">
                      <span className="font-semibold text-zinc-900 dark:text-zinc-100 truncate">{user.full_name}</span>
                      <span className="text-xs text-zinc-500 truncate">{user.email}</span>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>
        )}

        {/* List Conversations */}
        <div className="flex-1 overflow-y-auto custom-scrollbar px-2">
          {loading ? (
            <div className="flex items-center justify-center h-32">
              <Loader2 className="h-6 w-6 animate-spin text-zinc-300 dark:text-zinc-700" />
            </div>
          ) : conversations.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-zinc-400 dark:text-zinc-600 space-y-4">
              <div className="h-16 w-16 rounded-full bg-zinc-100 dark:bg-zinc-900 flex items-center justify-center">
                <MessageSquare className="h-8 w-8 text-zinc-300 dark:text-zinc-700" />
              </div>
              <p className="text-sm font-medium">Chưa có tin nhắn nào</p>
            </div>
          ) : (
            <div className="space-y-1 pb-4">
              {conversations.map((conv) => {
                const displayName = getConvDisplayName(conv);
                const isSelected = selectedConv?.conversation_id === conv.conversation_id;
                
                return (
                  <button
                    key={conv.conversation_id}
                    onClick={() => setSelectedConv(conv)}
                    className={`w-full text-left p-3 rounded-2xl flex items-center gap-3 transition-all ${
                      isSelected
                        ? "bg-blue-600 text-white shadow-md shadow-blue-500/20"
                        : "hover:bg-zinc-100 dark:hover:bg-zinc-900 text-zinc-900 dark:text-zinc-100"
                    }`}
                  >
                    {/* Avatar */}
                    <div className={`h-12 w-12 flex-shrink-0 rounded-full flex items-center justify-center font-bold text-lg shadow-sm ${
                      isSelected 
                        ? "bg-white/20 text-white" 
                        : "bg-gradient-to-br from-zinc-200 to-zinc-300 dark:from-zinc-800 dark:to-zinc-700 text-zinc-600 dark:text-zinc-300"
                    }`}>
                      {getInitials(displayName)}
                    </div>
                    
                    {/* Info */}
                    <div className="flex-1 overflow-hidden flex flex-col justify-center">
                      <div className="flex items-center justify-between mb-0.5">
                        <p className={`font-semibold truncate text-[15px] ${isSelected ? "text-white" : ""}`}>
                          {displayName}
                        </p>
                      </div>
                      <p className={`text-[13px] truncate ${isSelected ? "text-blue-100" : "text-zinc-500 dark:text-zinc-400"}`}>
                        {conv.type === "direct" ? "Trò chuyện trực tiếp" : `Nhóm ${conv.participants?.length || 0} thành viên`}
                      </p>
                    </div>
                  </button>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* ── Chat area (Telegram-like slide over for mobile) ── */}
      <div
        className={`
          fixed inset-0 z-50 md:static md:flex-1
          flex flex-col bg-[#f4f4f5] dark:bg-zinc-950 md:z-auto
          transition-transform duration-300 ease-[cubic-bezier(0.32,0.72,0,1)]
          ${selectedConv ? "translate-x-0" : "translate-x-full md:translate-x-0"}
        `}
      >
        {selectedConv ? (
          <>
            {/* Chat Header */}
            <div className="shrink-0 flex items-center gap-3 bg-white/80 dark:bg-zinc-950/80 backdrop-blur-md border-b border-zinc-200 dark:border-zinc-800 px-2 py-2.5 z-10 shadow-sm md:shadow-none pt-[max(0.5rem,env(safe-area-inset-top))]">
              <button
                onClick={() => setSelectedConv(null)}
                className="md:hidden rounded-full p-2.5 text-blue-600 dark:text-blue-400 hover:bg-zinc-100 dark:hover:bg-zinc-900 transition-colors active:scale-95"
              >
                <ArrowLeft className="h-6 w-6" strokeWidth={2.5} />
              </button>
              
              <div className="h-10 w-10 flex-shrink-0 rounded-full flex items-center justify-center font-bold text-white bg-gradient-to-br from-blue-500 to-indigo-500 shadow-sm ml-1 md:ml-3">
                {getInitials(getConvDisplayName(selectedConv))}
              </div>
              
              <div className="flex-1 overflow-hidden cursor-pointer">
                <p className="text-base font-bold text-zinc-900 dark:text-zinc-100 truncate tracking-tight">
                  {getConvDisplayName(selectedConv)}
                </p>
                <p className="text-[12px] text-zinc-500 dark:text-zinc-400 truncate">
                  {selectedConv.type === "direct" ? "Đang trực tuyến" : `${selectedConv.participants?.length || 0} thành viên`}
                </p>
              </div>
            </div>

            {/* Messages Area */}
            <div
              ref={messagesContainerRef}
              onScroll={handleScroll}
              className="flex-1 overflow-y-auto p-4 space-y-4 bg-[#e5e5ea] dark:bg-[#000000] relative scroll-smooth"
            >
              {/* Load more indicator */}
              {loadingMore && (
                <div className="flex justify-center py-3 sticky top-0 z-10">
                  <div className="bg-white/80 dark:bg-zinc-900/80 backdrop-blur-sm shadow-sm rounded-full px-4 py-1.5 flex items-center gap-2 border border-zinc-200 dark:border-zinc-800">
                    <Loader2 className="h-4 w-4 animate-spin text-blue-600" />
                    <span className="text-xs font-medium text-zinc-600 dark:text-zinc-400">Đang tải lịch sử...</span>
                  </div>
                </div>
              )}
              
              {!hasMore && messages.length > 0 && (
                <div className="flex justify-center py-4">
                  <div className="bg-zinc-200/60 dark:bg-zinc-800/60 rounded-xl px-4 py-1.5">
                    <p className="text-[11px] font-medium text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">
                      Khởi đầu cuộc trò chuyện
                    </p>
                  </div>
                </div>
              )}

              {/* Message List */}
              {messages.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-full text-zinc-400 dark:text-zinc-500 opacity-60">
                  <div className="bg-zinc-200/50 dark:bg-zinc-800/50 p-6 rounded-3xl mb-4">
                    <MessageSquare className="h-10 w-10 text-zinc-500 dark:text-zinc-400" />
                  </div>
                  <p className="text-[15px] font-medium text-zinc-600 dark:text-zinc-400">Gửi lời chào đầu tiên!</p>
                </div>
              ) : (
                <div className="flex flex-col gap-1 pb-4">
                  {messages.map((msg, index) => {
                    const isMine = msg.sender_id === currentUserId;
                    
                    // Logic to determine bubble shapes (consecutive messages)
                    const prevMsg = index > 0 ? messages[index - 1] : null;
                    const nextMsg = index < messages.length - 1 ? messages[index + 1] : null;
                    
                    const isFirstInGroup = !prevMsg || prevMsg.sender_id !== msg.sender_id;
                    const isLastInGroup = !nextMsg || nextMsg.sender_id !== msg.sender_id;
                    
                    return (
                      <div
                        key={msg.message_id}
                        className={`flex w-full ${isMine ? "justify-end pl-12" : "justify-start pr-12"} ${isFirstInGroup ? "mt-3" : "mt-0.5"}`}
                      >
                        <div
                          className={`max-w-full px-3.5 py-2.5 shadow-sm relative group
                            ${isMine 
                              ? "bg-blue-600 text-white" 
                              : "bg-white dark:bg-zinc-900 border border-zinc-100 dark:border-zinc-800 text-zinc-900 dark:text-zinc-100"
                            }
                            ${/* Smart Border Radius for Telegram feel */ ""}
                            ${isFirstInGroup && isLastInGroup ? "rounded-2xl" : ""}
                            ${!isFirstInGroup && !isLastInGroup && isMine ? "rounded-l-2xl rounded-r-sm" : ""}
                            ${!isFirstInGroup && !isLastInGroup && !isMine ? "rounded-r-2xl rounded-l-sm" : ""}
                            ${isFirstInGroup && !isLastInGroup && isMine ? "rounded-t-2xl rounded-bl-2xl rounded-br-sm" : ""}
                            ${isFirstInGroup && !isLastInGroup && !isMine ? "rounded-t-2xl rounded-br-2xl rounded-bl-sm" : ""}
                            ${!isFirstInGroup && isLastInGroup && isMine ? "rounded-b-2xl rounded-tl-2xl rounded-tr-sm" : ""}
                            ${!isFirstInGroup && isLastInGroup && !isMine ? "rounded-b-2xl rounded-tr-2xl rounded-tl-sm" : ""}
                          `}
                        >
                          {/* Sender Name for group chats if not mine */}
                          {!isMine && isFirstInGroup && selectedConv.type !== "direct" && (
                            <p className="text-[11px] font-bold text-blue-600 dark:text-blue-400 mb-1 leading-none">
                              {msg.sender_email.split('@')[0]}
                            </p>
                          )}
                          
                          <p className="text-[15px] leading-relaxed whitespace-pre-wrap break-words inline-block">
                            {msg.content}
                            {/* Inline spacer to push time to right */}
                            <span className="inline-block w-12" aria-hidden="true"></span>
                          </p>
                          
                          {/* Subtle Time Badge */}
                          <span
                            className={`absolute bottom-1.5 right-2 text-[10px] font-medium tracking-tight ${
                              isMine ? "text-blue-200" : "text-zinc-400 dark:text-zinc-600"
                            }`}
                          >
                            {formatTime(msg.created_at)}
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
              <div ref={messagesEndRef} className="h-2" />
            </div>

            {/* Input Area */}
            <div className="shrink-0 bg-white dark:bg-zinc-950 px-3 pt-3 pb-[max(0.75rem,env(safe-area-inset-bottom))] md:px-4 md:py-4 border-t border-zinc-200 dark:border-zinc-900">
              <div className="flex items-end gap-2 max-w-4xl mx-auto">
                {/* Plus Button (Attachment placeholder) */}
                <button className="flex-shrink-0 p-2.5 rounded-full text-zinc-400 hover:text-blue-600 hover:bg-blue-50 dark:hover:bg-zinc-900 transition-colors">
                  <Plus className="h-6 w-6" strokeWidth={2} />
                </button>
                
                <div className="flex-1 relative bg-zinc-100 dark:bg-zinc-900 rounded-3xl border border-transparent focus-within:border-blue-500 focus-within:bg-white dark:focus-within:bg-zinc-950 transition-all flex items-end">
                  <textarea
                    rows={1}
                    value={input}
                    onChange={(e) => {
                      setInput(e.target.value);
                      e.target.style.height = 'auto';
                      e.target.style.height = `${Math.min(e.target.scrollHeight, 120)}px`;
                    }}
                    onKeyDown={handleKeyDown}
                    placeholder="Nhắn tin..."
                    className="w-full bg-transparent border-none px-4 py-3 text-[15px] text-zinc-900 dark:text-zinc-100 placeholder-zinc-500 focus:outline-none focus:ring-0 resize-none max-h-[120px] rounded-3xl"
                    style={{ minHeight: '44px' }}
                  />
                </div>
                
                {/* Send Button */}
                <button
                  onClick={handleSend}
                  disabled={!input.trim()}
                  className={`flex-shrink-0 p-3 rounded-full transition-all duration-200 ${
                    input.trim() 
                      ? "bg-blue-600 text-white shadow-md shadow-blue-600/20 active:scale-90 hover:bg-blue-700" 
                      : "bg-zinc-100 dark:bg-zinc-900 text-zinc-400"
                  }`}
                >
                  <Send className="h-5 w-5" strokeWidth={2} style={{ transform: input.trim() ? "translate(1px, -1px)" : "none" }} />
                </button>
              </div>
            </div>
          </>
        ) : (
          /* Desktop Empty State (Hidden on Mobile due to slide logic) */
          <div className="hidden md:flex flex-col w-full items-center justify-center h-full bg-[#f4f4f5] dark:bg-zinc-950 text-zinc-400 dark:text-zinc-600">
            <div className="w-24 h-24 rounded-full bg-white dark:bg-zinc-900 shadow-sm flex items-center justify-center mb-6">
              <MessageSquare className="h-10 w-10 text-blue-500 opacity-60" />
            </div>
            <p className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-zinc-600 to-zinc-400">Ứng dụng Nhắn tin IRIS</p>
            <p className="text-sm font-medium mt-2">Chọn một cuộc trò chuyện để bắt đầu</p>
          </div>
        )}
      </div>
    </div>
  );
}
