// apps/web/src/components/shared/PostCard.tsx
import React from "react";
import { Post, PostComment } from "@/types";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { POST_SCOPE_LABELS, POST_TYPE_META } from "@/lib/post-config";
import { Heart, MessageCircle, SendHorizontal } from "lucide-react";
import { teacherApi } from "@/lib/api/teacher.api";
import { parentApi } from "@/lib/api/parent.api";

interface PostCardProps {
  post: Post;
  authorLabel?: string;
  enableInteractions?: boolean;
  enableShare?: boolean;
  audience?: "teacher" | "parent";
  onPostPatched?: (postId: string, patch: Partial<Post>) => void;
}

function getScopeDisplay(post: Post): string {
  return POST_SCOPE_LABELS[post.scope_type] || post.scope_type;
}

export function PostCard({
  post,
  authorLabel = "Giáo viên",
  enableInteractions = true,
  enableShare = true,
  audience = "teacher",
  onPostPatched,
}: PostCardProps) {
  const [liked, setLiked] = React.useState(post.liked_by_me);
  const [likeCount, setLikeCount] = React.useState(post.like_count || 0);
  const [shareCount, setShareCount] = React.useState(post.share_count || 0);
  const [commentCount, setCommentCount] = React.useState(post.comment_count || 0);
  const [showComments, setShowComments] = React.useState(false);
  const [commentDraft, setCommentDraft] = React.useState("");
  const [comments, setComments] = React.useState<PostComment[]>([]);
  const [commentsLoaded, setCommentsLoaded] = React.useState(false);
  const [loadingComments, setLoadingComments] = React.useState(false);
  const [submittingComment, setSubmittingComment] = React.useState(false);
  const [processingLike, setProcessingLike] = React.useState(false);
  const [processingShare, setProcessingShare] = React.useState(false);
  const [interactionError, setInteractionError] = React.useState("");

  const postApi = audience === "parent" ? parentApi : teacherApi;

  React.useEffect(() => {
    setLiked(post.liked_by_me);
    setLikeCount(post.like_count || 0);
    setShareCount(post.share_count || 0);
    setCommentCount(post.comment_count || 0);
  }, [post.liked_by_me, post.like_count, post.share_count, post.comment_count]);

  const postMeta = POST_TYPE_META[post.type] || {
    label: post.type,
    badgeVariant: "secondary" as const,
  };

  const patchPost = React.useCallback(
    (patch: Partial<Post>) => {
      onPostPatched?.(post.post_id, patch);
    },
    [onPostPatched, post.post_id],
  );

  const handleLikeToggle = async () => {
    try {
      setProcessingLike(true);
      setInteractionError("");
      const payload = await postApi.togglePostLike(post.post_id);
      setLiked(payload.liked_by_me);
      setLikeCount(payload.like_count);
      patchPost({ liked_by_me: payload.liked_by_me, like_count: payload.like_count });
    } catch {
      setInteractionError("Không thể cập nhật lượt thích. Vui lòng thử lại.");
    } finally {
      setProcessingLike(false);
    }
  };

  const loadComments = React.useCallback(async () => {
    try {
      setLoadingComments(true);
      setInteractionError("");
      const response = await postApi.getPostComments(post.post_id, { limit: 50, offset: 0 });
      setComments(response.data || []);
      setCommentsLoaded(true);
    } catch {
      setInteractionError("Không thể tải bình luận. Vui lòng thử lại.");
    } finally {
      setLoadingComments(false);
    }
  }, [post.post_id, postApi]);

  const handleShare = async () => {
    try {
      setProcessingShare(true);
      setInteractionError("");
      const payload = await postApi.sharePost(post.post_id);
      setShareCount(payload.share_count);
      patchPost({ share_count: payload.share_count });
    } catch {
      setInteractionError("Không thể chia sẻ bài viết. Vui lòng thử lại.");
    } finally {
      setProcessingShare(false);
    }
  };

  const handleCommentSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    const nextComment = commentDraft.trim();
    if (!nextComment) {
      return;
    }

    try {
      setSubmittingComment(true);
      setInteractionError("");
      const payload = await postApi.createPostComment(post.post_id, { content: nextComment });
      setComments((prev) => [payload.comment, ...prev]);
      setCommentCount(payload.comment_count);
      patchPost({ comment_count: payload.comment_count });
      setCommentDraft("");
    } catch {
      setInteractionError("Không thể gửi bình luận. Vui lòng thử lại.");
    } finally {
      setSubmittingComment(false);
    }
  };

  const handleToggleComments = async () => {
    const next = !showComments;
    setShowComments(next);

    if (next && !commentsLoaded) {
      await loadComments();
    }
  };

  return (
    <Card className="overflow-hidden">
      <CardContent className="space-y-3 p-4 sm:p-5">
        <div className="flex items-start justify-between gap-3">
          <div className="flex min-w-0 items-center gap-3">
            <Avatar>
              <AvatarFallback>GV</AvatarFallback>
            </Avatar>
            <div className="min-w-0">
              <p className="truncate text-sm font-semibold text-foreground">{authorLabel}</p>
              <p className="text-xs text-muted-foreground">
                {new Date(post.created_at).toLocaleString("vi-VN")} • {getScopeDisplay(post)}
              </p>
            </div>
          </div>
          <Badge variant={postMeta.badgeVariant}>{postMeta.label}</Badge>
        </div>

        <p className="whitespace-pre-line text-sm leading-6 text-foreground">{post.content}</p>

        {enableInteractions && (
          <>
            <div className="flex flex-wrap items-center gap-2 border-t pt-3">
              <Button
                type="button"
                size="sm"
                variant="ghost"
                className={liked ? "text-primary" : "text-muted-foreground"}
                onClick={handleLikeToggle}
                aria-pressed={liked}
                disabled={processingLike}
              >
                <Heart className="mr-1 h-4 w-4" />
                Thích ({likeCount})
              </Button>

              <Button
                type="button"
                size="sm"
                variant="ghost"
                className="text-muted-foreground"
                onClick={handleToggleComments}
                aria-expanded={showComments}
              >
                <MessageCircle className="mr-1 h-4 w-4" />
                Bình luận ({commentCount})
              </Button>

              {enableShare && (
                <Button
                  type="button"
                  size="sm"
                  variant="ghost"
                  className="text-muted-foreground"
                  onClick={handleShare}
                  disabled={processingShare}
                >
                  <SendHorizontal className="mr-1 h-4 w-4" />
                  Chia sẻ ({shareCount})
                </Button>
              )}
            </div>

            {interactionError && <p className="text-xs text-destructive">{interactionError}</p>}

            {showComments && (
              <div className="space-y-3 border-t pt-3">
                <form className="flex items-center gap-2" onSubmit={handleCommentSubmit}>
                  <Input
                    value={commentDraft}
                    onChange={(event) => setCommentDraft(event.target.value)}
                    placeholder="Viết bình luận..."
                    aria-label="Viết bình luận"
                  />
                  <Button type="submit" size="sm" disabled={!commentDraft.trim() || submittingComment}>
                    Gửi
                  </Button>
                </form>

                {loadingComments && <p className="text-xs text-muted-foreground">Đang tải bình luận...</p>}

                {!loadingComments && comments.length > 0 && (
                  <ul className="space-y-2">
                    {comments.map((comment) => (
                      <li key={comment.comment_id} className="rounded-md bg-muted/50 px-3 py-2 text-sm text-foreground">
                        <p className="text-xs font-medium text-muted-foreground">{comment.author_display}</p>
                        <p>{comment.content}</p>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            )}
          </>
        )}
      </CardContent>
    </Card>
  );
}

// apps/web/src/components/PostCard.vue
<script setup>
import { ref, watch } from 'vue'
import { Heart, MessageCircle, SendHorizontal } from 'lucide-vue-next'
import { teacherService } from '../services/teacherService'
import { parentService } from '../services/parentService'
import { POST_SCOPE_LABELS, POST_TYPE_META } from '../helpers/postConfig'

const props = defineProps({
  post: {
    type: Object,
    required: true,
  },
  authorLabel: {
    type: String,
    default: 'Giáo viên',
  },
  audience: {
    type: String,
    default: 'teacher',
  },
  enableInteractions: {
    type: Boolean,
    default: true,
  },
  enableShare: {
    type: Boolean,
    default: true,
  },
})

const emit = defineEmits(['patch-post'])

const liked = ref(props.post.liked_by_me)
const likeCount = ref(props.post.like_count || 0)
const shareCount = ref(props.post.share_count || 0)
const commentCount = ref(props.post.comment_count || 0)
const showComments = ref(false)
const comments = ref([])
const commentsLoaded = ref(false)
const commentDraft = ref('')
const loadingComments = ref(false)
const processingLike = ref(false)
const processingShare = ref(false)
const submittingComment = ref(false)
const interactionError = ref('')

const services = {
  teacher: teacherService,
  parent: parentService,
}

watch(
  () => props.post,
  (post) => {
    liked.value = post.liked_by_me
    likeCount.value = post.like_count || 0
    shareCount.value = post.share_count || 0
    commentCount.value = post.comment_count || 0
  },
  { deep: true },
)

function patchPost(patch) {
  emit('patch-post', props.post.post_id, patch)
}

function formatDateTime(value) {
  if (!value) return ''
  return new Date(value).toLocaleString('vi-VN')
}

function initials(text) {
  return (text || props.authorLabel || 'GV').slice(0, 2).toUpperCase()
}

async function handleLikeToggle() {
  processingLike.value = true
  interactionError.value = ''
  try {
    const response = await services[props.audience].togglePostLike(props.post.post_id)
    const payload = response?.data ?? response
    liked.value = payload.liked_by_me
    likeCount.value = payload.like_count
    patchPost({ liked_by_me: payload.liked_by_me, like_count: payload.like_count })
  } catch {
    interactionError.value = 'Không thể cập nhật lượt thích. Vui lòng thử lại.'
  } finally {
    processingLike.value = false
  }
}

async function loadComments() {
  loadingComments.value = true
  interactionError.value = ''
  try {
    const response = await services[props.audience].getPostComments(props.post.post_id, {
      limit: 50,
      offset: 0,
    })
    comments.value = response?.data ?? []
    commentsLoaded.value = true
  } catch {
    interactionError.value = 'Không thể tải bình luận. Vui lòng thử lại.'
  } finally {
    loadingComments.value = false
  }
}

async function toggleComments() {
  showComments.value = !showComments.value
  if (showComments.value && !commentsLoaded.value) {
    await loadComments()
  }
}

async function submitComment() {
  const content = commentDraft.value.trim()
  if (!content) return

  submittingComment.value = true
  interactionError.value = ''
  try {
    const response = await services[props.audience].createPostComment(props.post.post_id, {
      content,
    })
    const payload = response?.data ?? response
    if (payload.comment) {
      comments.value = [payload.comment, ...comments.value]
    }
    commentCount.value = payload.comment_count ?? commentCount.value + 1
    patchPost({ comment_count: commentCount.value })
    commentDraft.value = ''
  } catch {
    interactionError.value = 'Không thể gửi bình luận. Vui lòng thử lại.'
  } finally {
    submittingComment.value = false
  }
}

async function handleShare() {
  processingShare.value = true
  interactionError.value = ''
  try {
    const response = await services[props.audience].sharePost(props.post.post_id)
    const payload = response?.data ?? response
    shareCount.value = payload.share_count
    patchPost({ share_count: payload.share_count })
  } catch {
    interactionError.value = 'Không thể chia sẻ bài viết. Vui lòng thử lại.'
  } finally {
    processingShare.value = false
  }
}
</script>

<template>
  <article class="card post-card">
    <div class="post-card__body">
      <div class="post-card__header">
        <div class="post-card__author">
          <div class="post-card__avatar">{{ initials(authorLabel) }}</div>
          <div class="post-card__author-copy">
            <p class="post-card__author-name">{{ authorLabel }}</p>
            <p class="post-card__meta">
              {{ formatDateTime(post.created_at) }} ·
              {{ POST_SCOPE_LABELS[post.scope_type] || post.scope_type }}
            </p>
          </div>
        </div>
        <span class="badge" :class="POST_TYPE_META[post.type]?.badgeClass || 'badge--outline'">
          {{ POST_TYPE_META[post.type]?.label || post.type }}
        </span>
      </div>

      <p class="post-card__content">{{ post.content }}</p>

      <template v-if="enableInteractions">
        <div class="post-card__actions">
          <button
            type="button"
            class="post-card__action"
            :class="{ 'post-card__action--active': liked }"
            :disabled="processingLike"
            @click="handleLikeToggle"
          >
            <Heart :size="16" />
            Thích ({{ likeCount }})
          </button>

          <button type="button" class="post-card__action" @click="toggleComments">
            <MessageCircle :size="16" />
            Bình luận ({{ commentCount }})
          </button>

          <button
            v-if="enableShare"
            type="button"
            class="post-card__action"
            :disabled="processingShare"
            @click="handleShare"
          >
            <SendHorizontal :size="16" />
            Chia sẻ ({{ shareCount }})
          </button>
        </div>

        <p v-if="interactionError" class="form-error">{{ interactionError }}</p>

        <div v-if="showComments" class="post-card__comments">
          <form class="post-card__comment-form" @submit.prevent="submitComment">
            <input
              v-model="commentDraft"
              class="form-input"
              placeholder="Viết bình luận..."
              aria-label="Viết bình luận"
            />
            <button
              type="submit"
              class="btn btn--primary btn--sm"
              :disabled="!commentDraft.trim() || submittingComment"
            >
              Gửi
            </button>
          </form>

          <p v-if="loadingComments" class="text-xs text-muted">Đang tải bình luận...</p>
          <ul v-else-if="comments.length > 0" class="post-card__comment-list">
            <li v-for="comment in comments" :key="comment.comment_id" class="post-card__comment">
              <p class="post-card__comment-author">{{ comment.author_display }}</p>
              <p>{{ comment.content }}</p>
            </li>
          </ul>
        </div>
      </template>
    </div>
  </article>
</template>

<style scoped>
.post-card {
  overflow: hidden;
}

.post-card__body {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-3);
  padding: var(--spacing-4);
}

.post-card__header,
.post-card__author,
.post-card__actions,
.post-card__comment-form {
  display: flex;
  align-items: center;
}

.post-card__header {
  justify-content: space-between;
  gap: var(--spacing-3);
}

.post-card__author {
  min-width: 0;
  gap: var(--spacing-3);
}

.post-card__avatar {
  width: 2.5rem;
  height: 2.5rem;
  border-radius: var(--radius-full);
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--color-primary);
  color: var(--color-on-primary);
  font-weight: 700;
}

.post-card__author-copy {
  min-width: 0;
}

.post-card__author-name {
  margin: 0;
  font-size: var(--font-size-sm);
  font-weight: 700;
}

.post-card__meta {
  margin: 0;
  font-size: var(--font-size-xs);
  color: var(--color-text-muted);
}

.post-card__content {
  white-space: pre-line;
  font-size: var(--font-size-sm);
  line-height: 1.625;
}

.post-card__actions {
  flex-wrap: wrap;
  gap: var(--spacing-2);
  border-top: 1px solid var(--color-border);
  padding-top: var(--spacing-3);
}

.post-card__action {
  display: inline-flex;
  align-items: center;
  gap: var(--spacing-1);
  border: 0;
  background: transparent;
  color: var(--color-text-muted);
  border-radius: var(--radius-md);
  padding: var(--spacing-2) var(--spacing-3);
  font-size: var(--font-size-sm);
}

.post-card__action:hover {
  background: var(--color-background);
  color: var(--color-text);
}

.post-card__action--active {
  color: var(--color-primary);
}

.post-card__comments {
  border-top: 1px solid var(--color-border);
  padding-top: var(--spacing-3);
}

.post-card__comment-form {
  gap: var(--spacing-2);
  margin-bottom: var(--spacing-3);
}

.post-card__comment-list {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-2);
  list-style: none;
}

.post-card__comment {
  background: var(--color-background);
  border-radius: var(--radius-md);
  padding: var(--spacing-2) var(--spacing-3);
  font-size: var(--font-size-sm);
}

.post-card__comment-author {
  margin: 0 0 var(--spacing-1);
  color: var(--color-text-muted);
  font-size: var(--font-size-xs);
  font-weight: 700;
}
</style>
